spring:
  application:
    name: uol-desafio
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:h2:file:///./data/db
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-console
app:
  version: ^project.version^